### ISSUE TITLE
Wallet connect not working properly

### ISSUE THREAD

**Issue by hardyjosh** [dragonflysun/cyclo-site#18]
To reproduce:

1. Disconnect wallet - should see "connect to Flare Mainnet"
<img width="578" alt="image" src="https://github.com/dragonflysun/cyclo-site/assets/1190022/f2725dc3-324d-4f54-b5d6-4c3a2e8285e2">

2. Connect wallet - will see "Connected to Flare Mainnet"
<img width="835" alt="image" src="https://github.com/dragonflysun/cyclo-site/assets/1190022/6e08a5f0-5d08-4221-bd0e-7134e7203dbd">

If you click the button, you'll see the modal for the connected state, with a "disconnect" button.

<img width="559" alt="image" src="https://github.com/dragonflysun/cyclo-site/assets/1190022/29ea8f08-9557-4508-be82-3bbd0b00a1e2">

4. Refresh the page
5. Click the button - you'll see the modal for when a wallet isn't connected. If you attempt to connect now by, for example clicking "Metamask" you'll get an error.

<img width="989" alt="image" src="https://github.com/dragonflysun/cyclo-site/assets/1190022/b2619ae0-b782-4850-83d9-326276f086b3">

**Comment by hardingjam** [comment]
6. To add - if you click the MM icon in your extensions then it opens the Metamask modal, and after that the walletConnect works again (displaying the 'connected' state)

**Comment by hardingjam** [comment]
Appears that an "init" isn't happening on refresh, either in walleconnect or svelte-wagmi
